# Generated by Django 2.2.13 on 2022-06-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220609_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
